#!/usr/bin/env python3
"""生成网站静态文件"""

import json
import shutil
from datetime import datetime
from pathlib import Path

# 读取最新数据
files = sorted(Path('data').glob('test_*.json'))
if not files:
    print('❌ 无数据文件')
    exit(1)

with open(files[-1]) as f:
    data = json.load(f)

# 创建 site 目录
Path('site').mkdir(exist_ok=True)

# 生成 index.html
html_content = f'''<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>CEX Intelligence Report</title>
    <style>
        body {{ font-family: -apple-system, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; background: #f5f5f5; }}
        h1 {{ color: #333; border-bottom: 2px solid #ddd; padding-bottom: 10px; }}
        .timestamp {{ color: #666; font-size: 14px; }}
        .status {{ padding: 15px 20px; border-radius: 8px; margin: 20px 0; font-weight: bold; }}
        .ok {{ background: #d4edda; color: #155724; }}
        .alert {{ background: #f8d7da; color: #721c24; }}
        .exchange {{ padding: 15px; border: 1px solid #ddd; border-radius: 8px; margin: 10px 0; background: white; }}
        .alert-level {{ font-size: 12px; padding: 2px 8px; border-radius: 4px; margin-left: 10px; }}
        .none {{ background: #d4edda; }}
        .low {{ background: #fff3cd; }}
        .medium {{ background: #ffe0b2; }}
        .high {{ background: #ffccbc; }}
        .critical {{ background: #ff8a80; color: white; }}
    </style>
</head>
<body>
    <h1>🎯 CEX 情报监控报告</h1>
    <p class="timestamp">⏰ 生成时间: {data.get('timestamp', 'N/A')}</p>
    <p class="timestamp">🤖 模型: {data.get('model', 'N/A')}</p>
    
    <div class="status {'alert' if data.get('key_alerts') else 'ok'}">
        {'🚨 发现 ' + str(len(data.get('key_alerts', []))) + ' 项警报' if data.get('key_alerts') else '✅ 今日监控正常，未发现重大风险'}
    </div>
    
    <h2>📊 监控交易所 ({len(data.get('exchanges', []))} 个)</h2>
    {''.join(f'<div class="exchange"><strong>{e.get("exchange")}</strong><span class="alert-level {e.get("alert_level", "none")}">{e.get("alert_level", "none").upper()}</span><br><small>🐦 X帖子: {len(e.get("x_posts", []))} | 📰 新闻: {len(e.get("web_articles", []))}</small></div>' for e in data.get('exchanges', []))}
    
    <p style="margin-top: 40px; color: #999; font-size: 12px; text-align: center;">
        🔄 自动 generated by CEX Intelligence Bot | 每日 09:00 更新
    </p>
</body>
</html>'''

with open('site/index.html', 'w', encoding='utf-8') as f:
    f.write(html_content)

# 复制 JSON 数据
shutil.copy(files[-1], 'site/data.json')

print('✅ 网站文件已生成:')
print('  - site/index.html')
print('  - site/data.json')
